# Generated by Django 3.0 on 2021-12-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('ADMIN', 'admin'), ('MODERATOR', 'moderator')], default='USER', help_text='Роль пользователя', max_length=150, verbose_name='Роль'),
        ),
    ]
