# Generated by Django 2.2.16 on 2021-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211130_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'moderaor'), (3, 'admin')], default=1),
            preserve_default=False,
        ),
    ]
