# Generated by Django 2.2.16 on 2021-11-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'moderator'), (3, 'admin')]),
        ),
    ]
