# Generated by Django 2.2.16 on 2021-11-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_user_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
