# Generated by Django 2.2.16 on 2021-12-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20211201_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default='user'),
        ),
    ]
