# Generated by Django 2.2.16 on 2021-12-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20211201_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique-in-module',
        ),
    ]
