# Generated by Django 2.2.16 on 2021-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20211201_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(choices=[(1, 'user'), (2, 'moderator'), (3, 'admin')], default=(2, 'moderator'), max_length=150),
        ),
    ]
