# Generated by Django 2.2.16 on 2021-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20211201_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.PositiveSmallIntegerField(max_length=200),
        ),
    ]
