# Generated by Django 2.2.16 on 2021-12-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20211201_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'user'), (2, 'moderator'), (3, 'admin')], default='user', max_length=150),
        ),
    ]
